### ISSUE TITLE
Docker環境構築

### ISSUE THREAD

**Issue by aokisinn** [aokisinn/bukumane#5]
Laravel 7系
MySql 新しめのやつ希望です
他は好みで！

**Comment by tanaka-kento** [comment]
@aokisinn Docker環境作ったのであとでプルリク出します!

**Comment by aokisinn** [comment]
@tanaka-kento 
対応あざっすーー
速スギィーーーーーー

**Comment by tanaka-kento** [comment]
@aokisinn mainにコミットしたのでissueクローズお願いします
